### ISSUE TITLE
iphone backup from icloud

### ISSUE THREAD

**Issue by vipinbeni** [alexhulbert/Cryogen#9]
Hi Sir , i use 
https://code.google.com/p/iphone-dataprotection/source/browse/python_scripts/icloud/backup.py

to download icloud backup but i m getting less file some file is missing like bookmark file and some image from camera roll 

i use a third party software to compare these changes  

as i see ur working on similar task please help me 

i download list file of  both software  and compare both file in winhex hex editor then i got  difference in these files

 list file is not showing more then 100 file in almost all backup it show 100 file.
please help me.

 please help me

**Comment by alexhulbert** [comment]
That backup program is semi-outdatted and buggy. Unfortunately, do to some major bugs (and my lack of sufficient python knowledge), I am unable to provide any support.
